//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Finance.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о приложении.
        /// </summary>
        public static string AboutSmall {
            get {
                return ResourceManager.GetString("AboutSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите валюту..
        /// </summary>
        public static string AccountCurrencyEmptyMessageText {
            get {
                return ResourceManager.GetString("AccountCurrencyEmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВАЛЮТА?.
        /// </summary>
        public static string AccountCurrencyEmptyMessageTitle {
            get {
                return ResourceManager.GetString("AccountCurrencyEmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удален.
        /// </summary>
        public static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить счет?.
        /// </summary>
        public static string AccountDeleteMessageText {
            get {
                return ResourceManager.GetString("AccountDeleteMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УДАЛЯТЬ?.
        /// </summary>
        public static string AccountDeleteMessageTitle {
            get {
                return ResourceManager.GetString("AccountDeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При удалении счета будут также удалены все транзакции связанные с ним..
        /// </summary>
        public static string AccountDeleteTransactionsMessageText {
            get {
                return ResourceManager.GetString("AccountDeleteTransactionsMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВАЖНО!.
        /// </summary>
        public static string AccountDeleteTransactionsMessageTitle {
            get {
                return ResourceManager.GetString("AccountDeleteTransactionsMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите счет..
        /// </summary>
        public static string AccountEmptyMessageText {
            get {
                return ResourceManager.GetString("AccountEmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СЧЕТ?.
        /// </summary>
        public static string AccountEmptyMessageTitle {
            get {
                return ResourceManager.GetString("AccountEmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название счета..
        /// </summary>
        public static string AccountNameEmptyMessageText {
            get {
                return ResourceManager.GetString("AccountNameEmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАЗВАНИЕ?.
        /// </summary>
        public static string AccountNameEmptyMessageTitle {
            get {
                return ResourceManager.GetString("AccountNameEmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счет.
        /// </summary>
        public static string AccountNormal {
            get {
                return ResourceManager.GetString("AccountNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to счет.
        /// </summary>
        public static string AccountSmall {
            get {
                return ResourceManager.GetString("AccountSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счета.
        /// </summary>
        public static string AccountsNormal {
            get {
                return ResourceManager.GetString("AccountsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to счета.
        /// </summary>
        public static string AccountsSmall {
            get {
                return ResourceManager.GetString("AccountsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать рекламу.
        /// </summary>
        public static string AdBlock {
            get {
                return ResourceManager.GetString("AdBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to добавить.
        /// </summary>
        public static string AddSmall {
            get {
                return ResourceManager.GetString("AddSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите сумму..
        /// </summary>
        public static string AmountEmptyMessageText {
            get {
                return ResourceManager.GetString("AmountEmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СКОЛЬКО?.
        /// </summary>
        public static string AmountEmptyMessageTitle {
            get {
                return ResourceManager.GetString("AmountEmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат суммы..
        /// </summary>
        public static string AmountIncorrectMessageText {
            get {
                return ResourceManager.GetString("AmountIncorrectMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СКОЛЬКО?.
        /// </summary>
        public static string AmountIncorrectMessageTitle {
            get {
                return ResourceManager.GetString("AmountIncorrectMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string AmountNormal {
            get {
                return ResourceManager.GetString("AmountNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансы+Долги - простое и удобное приложение для управления своими доходами и расходами, а также долгами и займами..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фон приложения.
        /// </summary>
        public static string ApplicationBackgroundNormal {
            get {
                return ResourceManager.GetString("ApplicationBackgroundNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИНАНСЫ+ДОЛГИ.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансы+Долги.
        /// </summary>
        public static string ApplicationTitleNormal {
            get {
                return ResourceManager.GetString("ApplicationTitleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход выполнен!.
        /// </summary>
        public static string AuthentificationCompleted {
            get {
                return ResourceManager.GetString("AuthentificationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается войти..
        /// </summary>
        public static string AuthentificationFailed {
            get {
                return ResourceManager.GetString("AuthentificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматически обновлять курсы валют.
        /// </summary>
        public static string AutoUpdateRatesNormal {
            get {
                return ResourceManager.GetString("AutoUpdateRatesNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать резервную копию.
        /// </summary>
        public static string BackupData {
            get {
                return ResourceManager.GetString("BackupData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая резервная копия заменит старую. Продолжить?.
        /// </summary>
        public static string BackupWarningMessageText {
            get {
                return ResourceManager.GetString("BackupWarningMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВНИМАНИЕ!.
        /// </summary>
        public static string BackupWarningMessageTitle {
            get {
                return ResourceManager.GetString("BackupWarningMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to назад.
        /// </summary>
        public static string BackwardSmall {
            get {
                return ResourceManager.GetString("BackwardSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        public static string BalanceNormal {
            get {
                return ResourceManager.GetString("BalanceNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to баланс.
        /// </summary>
        public static string BalanceSmall {
            get {
                return ResourceManager.GetString("BalanceSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отмена.
        /// </summary>
        public static string CancelSmall {
            get {
                return ResourceManager.GetString("CancelSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осуществить возврат денег на соответсвующие счета?.
        /// </summary>
        public static string CashbackMessageText {
            get {
                return ResourceManager.GetString("CashbackMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДЕНЬГИ?.
        /// </summary>
        public static string CashbackMessageTitle {
            get {
                return ResourceManager.GetString("CashbackMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string CategoriesNormal {
            get {
                return ResourceManager.GetString("CategoriesNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to категории.
        /// </summary>
        public static string CategoriesSmall {
            get {
                return ResourceManager.GetString("CategoriesSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить категорию?.
        /// </summary>
        public static string CategoryDeleteMessageText {
            get {
                return ResourceManager.GetString("CategoryDeleteMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УДАЛЯТЬ?.
        /// </summary>
        public static string CategoryDeleteMessageTitle {
            get {
                return ResourceManager.GetString("CategoryDeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При удалении категории будут также удалены все транзакции этой категории..
        /// </summary>
        public static string CategoryDeleteTransactionsMessageText {
            get {
                return ResourceManager.GetString("CategoryDeleteTransactionsMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВАЖНО!.
        /// </summary>
        public static string CategoryDeleteTransactionsMessageTitle {
            get {
                return ResourceManager.GetString("CategoryDeleteTransactionsMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите категорию..
        /// </summary>
        public static string CategoryEmptyMessageText {
            get {
                return ResourceManager.GetString("CategoryEmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КАТЕГОРИЯ?.
        /// </summary>
        public static string CategoryEmptyMessageTitle {
            get {
                return ResourceManager.GetString("CategoryEmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название категории..
        /// </summary>
        public static string CategoryNameEmptyMessageText {
            get {
                return ResourceManager.GetString("CategoryNameEmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАЗВАНИЕ?.
        /// </summary>
        public static string CategoryNameEmptyMessageTitle {
            get {
                return ResourceManager.GetString("CategoryNameEmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string CategoryNormal {
            get {
                return ResourceManager.GetString("CategoryNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to категория.
        /// </summary>
        public static string CategorySmall {
            get {
                return ResourceManager.GetString("CategorySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выбрать.
        /// </summary>
        public static string ChooseSmall {
            get {
                return ResourceManager.GetString("ChooseSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюты.
        /// </summary>
        public static string CurrenciesNormal {
            get {
                return ResourceManager.GetString("CurrenciesNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to валюты.
        /// </summary>
        public static string CurrenciesSmall {
            get {
                return ResourceManager.GetString("CurrenciesSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Армянский драм.
        /// </summary>
        public static string CurrencyAMD {
            get {
                return ResourceManager.GetString("CurrencyAMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Австралийский доллар.
        /// </summary>
        public static string CurrencyAUD {
            get {
                return ResourceManager.GetString("CurrencyAUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Азербайджанский манат.
        /// </summary>
        public static string CurrencyAZN {
            get {
                return ResourceManager.GetString("CurrencyAZN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болгарский лев.
        /// </summary>
        public static string CurrencyBGN {
            get {
                return ResourceManager.GetString("CurrencyBGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бразильский реал.
        /// </summary>
        public static string CurrencyBRL {
            get {
                return ResourceManager.GetString("CurrencyBRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Белорусский рубль.
        /// </summary>
        public static string CurrencyBYR {
            get {
                return ResourceManager.GetString("CurrencyBYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канадский доллар.
        /// </summary>
        public static string CurrencyCAD {
            get {
                return ResourceManager.GetString("CurrencyCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Швейцарский франк.
        /// </summary>
        public static string CurrencyCHF {
            get {
                return ResourceManager.GetString("CurrencyCHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Китайский юань.
        /// </summary>
        public static string CurrencyCNY {
            get {
                return ResourceManager.GetString("CurrencyCNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чешская крона.
        /// </summary>
        public static string CurrencyCZK {
            get {
                return ResourceManager.GetString("CurrencyCZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датская крона.
        /// </summary>
        public static string CurrencyDKK {
            get {
                return ResourceManager.GetString("CurrencyDKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Евро.
        /// </summary>
        public static string CurrencyEUR {
            get {
                return ResourceManager.GetString("CurrencyEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фунт стерлингов.
        /// </summary>
        public static string CurrencyGBP {
            get {
                return ResourceManager.GetString("CurrencyGBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Венгерский Форинт.
        /// </summary>
        public static string CurrencyHUF {
            get {
                return ResourceManager.GetString("CurrencyHUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индийская рупия.
        /// </summary>
        public static string CurrencyINR {
            get {
                return ResourceManager.GetString("CurrencyINR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Японская иена.
        /// </summary>
        public static string CurrencyJPY {
            get {
                return ResourceManager.GetString("CurrencyJPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Киргизский cом.
        /// </summary>
        public static string CurrencyKGS {
            get {
                return ResourceManager.GetString("CurrencyKGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вон Республики Корея.
        /// </summary>
        public static string CurrencyKRW {
            get {
                return ResourceManager.GetString("CurrencyKRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Казахстанский тенге.
        /// </summary>
        public static string CurrencyKZT {
            get {
                return ResourceManager.GetString("CurrencyKZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Молдавский лей.
        /// </summary>
        public static string CurrencyMDL {
            get {
                return ResourceManager.GetString("CurrencyMDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Норвежская крона.
        /// </summary>
        public static string CurrencyNOK {
            get {
                return ResourceManager.GetString("CurrencyNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюта.
        /// </summary>
        public static string CurrencyNormal {
            get {
                return ResourceManager.GetString("CurrencyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Польский злотый.
        /// </summary>
        public static string CurrencyPLN {
            get {
                return ResourceManager.GetString("CurrencyPLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнее обновление.
        /// </summary>
        public static string CurrencyRatesLastUpdate {
            get {
                return ResourceManager.GetString("CurrencyRatesLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to курсы валют.
        /// </summary>
        public static string CurrencyRatesSmall {
            get {
                return ResourceManager.GetString("CurrencyRatesSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый румынский лей.
        /// </summary>
        public static string CurrencyRON {
            get {
                return ResourceManager.GetString("CurrencyRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Российский рубль.
        /// </summary>
        public static string CurrencyRUB {
            get {
                return ResourceManager.GetString("CurrencyRUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шведская крона.
        /// </summary>
        public static string CurrencySEK {
            get {
                return ResourceManager.GetString("CurrencySEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сингапурский доллар.
        /// </summary>
        public static string CurrencySGD {
            get {
                return ResourceManager.GetString("CurrencySGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to валюта.
        /// </summary>
        public static string CurrencySmall {
            get {
                return ResourceManager.GetString("CurrencySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таджикский сомони.
        /// </summary>
        public static string CurrencyTJS {
            get {
                return ResourceManager.GetString("CurrencyTJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый туркменский манат.
        /// </summary>
        public static string CurrencyTMT {
            get {
                return ResourceManager.GetString("CurrencyTMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Турецкая лира.
        /// </summary>
        public static string CurrencyTRY {
            get {
                return ResourceManager.GetString("CurrencyTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Украинская гривна.
        /// </summary>
        public static string CurrencyUAH {
            get {
                return ResourceManager.GetString("CurrencyUAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доллар США.
        /// </summary>
        public static string CurrencyUSD {
            get {
                return ResourceManager.GetString("CurrencyUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узбекский сум.
        /// </summary>
        public static string CurrencyUZS {
            get {
                return ResourceManager.GetString("CurrencyUZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СДР.
        /// </summary>
        public static string CurrencyXDR {
            get {
                return ResourceManager.GetString("CurrencyXDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Южноафриканский рэнд.
        /// </summary>
        public static string CurrencyZAR {
            get {
                return ResourceManager.GetString("CurrencyZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основная валюта.
        /// </summary>
        public static string CurrentCurrencyNormal {
            get {
                return ResourceManager.GetString("CurrentCurrencyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенос базы данных....
        /// </summary>
        public static string DatabaseMigration {
            get {
                return ResourceManager.GetString("DatabaseMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все данные удалены..
        /// </summary>
        public static string DataDeletedMessageText {
            get {
                return ResourceManager.GetString("DataDeletedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УДАЛЕНО!.
        /// </summary>
        public static string DataDeletedMEssageTitle {
            get {
                return ResourceManager.GetString("DataDeletedMEssageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные.
        /// </summary>
        public static string DataNormal {
            get {
                return ResourceManager.GetString("DataNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to данные.
        /// </summary>
        public static string DataSmall {
            get {
                return ResourceManager.GetString("DataSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string DateFromNormal {
            get {
                return ResourceManager.GetString("DateFromNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string DateNormal {
            get {
                return ResourceManager.GetString("DateNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По.
        /// </summary>
        public static string DateToNormal {
            get {
                return ResourceManager.GetString("DateToNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to день.
        /// </summary>
        public static string DaySmall {
            get {
                return ResourceManager.GetString("DaySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to долг.
        /// </summary>
        public static string DebtSmall {
            get {
                return ResourceManager.GetString("DebtSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долги.
        /// </summary>
        public static string DebtsNormal {
            get {
                return ResourceManager.GetString("DebtsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to долги.
        /// </summary>
        public static string DebtsSmall {
            get {
                return ResourceManager.GetString("DebtsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить данные.
        /// </summary>
        public static string DeleteData {
            get {
                return ResourceManager.GetString("DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить все данные?.
        /// </summary>
        public static string DeleteDataWarnindMessageText {
            get {
                return ResourceManager.GetString("DeleteDataWarnindMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УДАЛИТЬ?.
        /// </summary>
        public static string DeleteDataWarnindMessageTitle {
            get {
                return ResourceManager.GetString("DeleteDataWarnindMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удаленные.
        /// </summary>
        public static string DeletedSmall {
            get {
                return ResourceManager.GetString("DeletedSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to удалить.
        /// </summary>
        public static string DeleteSmall {
            get {
                return ResourceManager.GetString("DeleteSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление....
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string DescriptionNormal {
            get {
                return ResourceManager.GetString("DescriptionNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено!.
        /// </summary>
        public static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается получить..
        /// </summary>
        public static string DownloadingFailed {
            get {
                return ResourceManager.GetString("DownloadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to изменить.
        /// </summary>
        public static string EditSmall {
            get {
                return ResourceManager.GetString("EditSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        public static string EmailNormal {
            get {
                return ResourceManager.GetString("EmailNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустое поле..
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОШИБКА!.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход.
        /// </summary>
        public static string ExpenceNormal {
            get {
                return ResourceManager.GetString("ExpenceNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расходы.
        /// </summary>
        public static string ExpencesNormal {
            get {
                return ResourceManager.GetString("ExpencesNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to расходы.
        /// </summary>
        public static string ExpencesSmall {
            get {
                return ResourceManager.GetString("ExpencesSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить все транзакции этого человека?.
        /// </summary>
        public static string ForgetMessageText {
            get {
                return ResourceManager.GetString("ForgetMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАБЫТЬ?.
        /// </summary>
        public static string ForgetMessageTitle {
            get {
                return ResourceManager.GetString("ForgetMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to забыть.
        /// </summary>
        public static string ForgetSmall {
            get {
                return ResourceManager.GetString("ForgetSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вперед.
        /// </summary>
        public static string ForwardSmall {
            get {
                return ResourceManager.GetString("ForwardSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откуда.
        /// </summary>
        public static string FromNormal {
            get {
                return ResourceManager.GetString("FromNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные.
        /// </summary>
        public static string GeneralNormal {
            get {
                return ResourceManager.GetString("GeneralNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to основные.
        /// </summary>
        public static string GeneralSmall {
            get {
                return ResourceManager.GetString("GeneralSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дать.
        /// </summary>
        public static string GiveNormal {
            get {
                return ResourceManager.GetString("GiveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дать.
        /// </summary>
        public static string GiveSmall {
            get {
                return ResourceManager.GetString("GiveSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доход.
        /// </summary>
        public static string IncomeNormal {
            get {
                return ResourceManager.GetString("IncomeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доходы.
        /// </summary>
        public static string IncomesNormal {
            get {
                return ResourceManager.GetString("IncomesNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to доходы.
        /// </summary>
        public static string IncomesSmall {
            get {
                return ResourceManager.GetString("IncomesSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string LanguageNormal {
            get {
                return ResourceManager.GetString("LanguageNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последняя синхронизация.
        /// </summary>
        public static string LastBackupDateText {
            get {
                return ResourceManager.GetString("LastBackupDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оценить.
        /// </summary>
        public static string LikeSmall {
            get {
                return ResourceManager.GetString("LikeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плитки.
        /// </summary>
        public static string LiveTileNormal {
            get {
                return ResourceManager.GetString("LiveTileNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to плитки.
        /// </summary>
        public static string LiveTileSmall {
            get {
                return ResourceManager.GetString("LiveTileSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается загрузить курсы валют..
        /// </summary>
        public static string LostConnectionMessageText {
            get {
                return ResourceManager.GetString("LostConnectionMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОШИБКА ПОДКЛЮЧЕНИЯ.
        /// </summary>
        public static string LostConnectionMessageTitle {
            get {
                return ResourceManager.GetString("LostConnectionMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to месяц.
        /// </summary>
        public static string MonthSmall {
            get {
                return ResourceManager.GetString("MonthSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string NameNormal {
            get {
                return ResourceManager.GetString("NameNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to никогда.
        /// </summary>
        public static string NeverSmall {
            get {
                return ResourceManager.GetString("NeverSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных для отображения....
        /// </summary>
        public static string NoDataMessage {
            get {
                return ResourceManager.GetString("NoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество знаков после запятой.
        /// </summary>
        public static string NumberOfDigits {
            get {
                return ResourceManager.GetString("NumberOfDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите погасить долг?.
        /// </summary>
        public static string PayOffMessageText {
            get {
                return ResourceManager.GetString("PayOffMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОГАСИТЬ?.
        /// </summary>
        public static string PayOffMessageTitle {
            get {
                return ResourceManager.GetString("PayOffMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Люди.
        /// </summary>
        public static string PeopleNormal {
            get {
                return ResourceManager.GetString("PeopleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to люди.
        /// </summary>
        public static string PeopleSmall {
            get {
                return ResourceManager.GetString("PeopleSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  в день.
        /// </summary>
        public static string PerDay {
            get {
                return ResourceManager.GetString("PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в среднем за день.
        /// </summary>
        public static string PerDayAvgSmall {
            get {
                return ResourceManager.GetString("PerDayAvgSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить человека?.
        /// </summary>
        public static string PersonDeleteMessageText {
            get {
                return ResourceManager.GetString("PersonDeleteMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УДАЛЯТЬ?.
        /// </summary>
        public static string PersonDeleteMessageTitle {
            get {
                return ResourceManager.GetString("PersonDeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При удалении человека будут также удалены все транзакции, связанные с ним..
        /// </summary>
        public static string PersonDeleteTransactionsMessageText {
            get {
                return ResourceManager.GetString("PersonDeleteTransactionsMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВАЖНО!.
        /// </summary>
        public static string PersonDeleteTransactionsMessageTitle {
            get {
                return ResourceManager.GetString("PersonDeleteTransactionsMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите человека..
        /// </summary>
        public static string PersonEmptyMessageText {
            get {
                return ResourceManager.GetString("PersonEmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КТО?.
        /// </summary>
        public static string PersonEmptyMessageTitle {
            get {
                return ResourceManager.GetString("PersonEmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя человека..
        /// </summary>
        public static string PersonNameEmptyMessageText {
            get {
                return ResourceManager.GetString("PersonNameEmptyMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КТО?.
        /// </summary>
        public static string PersonNameEmptyMessageTitle {
            get {
                return ResourceManager.GetString("PersonNameEmptyMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string PersonNameNormal {
            get {
                return ResourceManager.GetString("PersonNameNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек.
        /// </summary>
        public static string PersonNormal {
            get {
                return ResourceManager.GetString("PersonNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string PersonPhoneNormal {
            get {
                return ResourceManager.GetString("PersonPhoneNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to человек.
        /// </summary>
        public static string PersonSmall {
            get {
                return ResourceManager.GetString("PersonSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезапустите приложение....
        /// </summary>
        public static string ReloadApp {
            get {
                return ResourceManager.GetString("ReloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to погасить.
        /// </summary>
        public static string RepaySmall {
            get {
                return ResourceManager.GetString("RepaySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить из резервной копии.
        /// </summary>
        public static string RestoreData {
            get {
                return ResourceManager.GetString("RestoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to восстановить.
        /// </summary>
        public static string RestoreSmall {
            get {
                return ResourceManager.GetString("RestoreSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервная копия заменит текущую базу данных. Продолжить?.
        /// </summary>
        public static string RestoreWarningMessageText {
            get {
                return ResourceManager.GetString("RestoreWarningMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВНИМАНИЕ!.
        /// </summary>
        public static string RestoreWarningMessageTitle {
            get {
                return ResourceManager.GetString("RestoreWarningMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление....
        /// </summary>
        public static string Restoring {
            get {
                return ResourceManager.GetString("Restoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сохранить.
        /// </summary>
        public static string SaveSmall {
            get {
                return ResourceManager.GetString("SaveSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выбрать фото.
        /// </summary>
        public static string SelectPhotoSmall {
            get {
                return ResourceManager.GetString("SelectPhotoSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to настройки.
        /// </summary>
        public static string SettingsSmall {
            get {
                return ResourceManager.GetString("SettingsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать копейки.
        /// </summary>
        public static string ShowPenny {
            get {
                return ResourceManager.GetString("ShowPenny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите..
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется вход....
        /// </summary>
        public static string SigningIn {
            get {
                return ResourceManager.GetString("SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string SignOutButton {
            get {
                return ResourceManager.GetString("SignOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to статистика.
        /// </summary>
        public static string StatisticsSmall {
            get {
                return ResourceManager.GetString("StatisticsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взять.
        /// </summary>
        public static string TakeNormal {
            get {
                return ResourceManager.GetString("TakeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to взять.
        /// </summary>
        public static string TakeSmall {
            get {
                return ResourceManager.GetString("TakeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string TimeNormal {
            get {
                return ResourceManager.GetString("TimeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        public static string TodayNormal {
            get {
                return ResourceManager.GetString("TodayNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сегодня.
        /// </summary>
        public static string TodaySmall {
            get {
                return ResourceManager.GetString("TodaySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куда.
        /// </summary>
        public static string ToNormal {
            get {
                return ResourceManager.GetString("ToNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        public static string TotalNormal {
            get {
                return ResourceManager.GetString("TotalNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить транзакции?.
        /// </summary>
        public static string TransactionsDeleteMessageText {
            get {
                return ResourceManager.GetString("TransactionsDeleteMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УДАЛЯТЬ?.
        /// </summary>
        public static string TransactionsDeleteMessageTitle {
            get {
                return ResourceManager.GetString("TransactionsDeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to транзакция.
        /// </summary>
        public static string TransactionSmall {
            get {
                return ResourceManager.GetString("TransactionSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перевод.
        /// </summary>
        public static string TransferSmall {
            get {
                return ResourceManager.GetString("TransferSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачный интерфейс.
        /// </summary>
        public static string TransparentInterface {
            get {
                return ResourceManager.GetString("TransparentInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачный тайл.
        /// </summary>
        public static string TransparentTile {
            get {
                return ResourceManager.GetString("TransparentTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная функция недоступна в пробной версии. Купить полную версию?.
        /// </summary>
        public static string TrialMessageText {
            get {
                return ResourceManager.GetString("TrialMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДЕМО-ВЕРСИЯ.
        /// </summary>
        public static string TrialMessageTitle {
            get {
                return ResourceManager.GetString("TrialMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string TypeNormal {
            get {
                return ResourceManager.GetString("TypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подождите, выполняются необходимые обновления..
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обновить.
        /// </summary>
        public static string UpdateSmall {
            get {
                return ResourceManager.GetString("UpdateSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обновление.
        /// </summary>
        public static string UpdateTitleSmall {
            get {
                return ResourceManager.GetString("UpdateTitleSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление курсов валют....
        /// </summary>
        public static string UpdatingCurrencyRates {
            get {
                return ResourceManager.GetString("UpdatingCurrencyRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправлено!.
        /// </summary>
        public static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка....
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается отправить..
        /// </summary>
        public static string UploadingFailed {
            get {
                return ResourceManager.GetString("UploadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия.
        /// </summary>
        public static string VersionNormal {
            get {
                return ResourceManager.GetString("VersionNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to неделя.
        /// </summary>
        public static string WeekSmall {
            get {
                return ResourceManager.GetString("WeekSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to год.
        /// </summary>
        public static string YearSmall {
            get {
                return ResourceManager.GetString("YearSmall", resourceCulture);
            }
        }
    }
}
